### PR TITLE
Fix #2 - Rework handling of typedefs.

### LINKED ISSUE #2: Access Violation loading a custom typelib
http://www.dexwerx.com/VB6.tlb

FYI, `olewoo.exe` crashes but `oledump.exe` produces incorrect dump while stock `oleview.exe` seems to work.

### PR DESCRIPTION
**Pull request by leibnitz27**
I'm going to leave this up for anyone who has an opinion for a few days.

Looks like I never properly handled typedefs - I've created a fairly basic sample DLL which ticks all the boxes I think are needed.

There's something interesting going on with tags of blobs, but that's a future game ;)

[typedeflib.dll.txt](https://github.com/leibnitz27/olewoo/files/4677317/typedeflib.dll.txt)

### CODE REVIEW

File: olewoo_interop/typestring.cpp [hunk 1]
```diff
@@ -74,17 +74,17 @@ void stringifyTypeDesc(TYPEDESC* typeDesc, ITypeInfo* pTypeInfo, IDLFormatter_io
...
+    case VT_CY: ift->AddString( "CURRENCY"); return;
     case VT_DATE: ift->AddString( "DATE"); return;
     case VT_BSTR: ift->AddString( "BSTR"); return;
     case VT_DISPATCH: ift->AddString( "IDispatch*"); return;
     case VT_ERROR: ift->AddString( "SCODE"); return;
     case VT_BOOL: ift->AddString( "VARIANT_BOOL"); return;
     case VT_VARIANT: ift->AddString( "VARIANT"); return;
     case VT_UNKNOWN: ift->AddString( "IUnknown*"); return;
-    case VT_UI1: ift->AddString( "BYTE"); return;
+    case VT_UI1: ift->AddString( "unsigned char"); return;
```
Comment (bclothier) [inline olewoo_interop/typestring.cpp:87]: A bit unsure about this.
```
 typedef byte BYTE;
```
[Source](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-oaut/25955917-9c7b-4153-9dd4-d229d77c3ede)

Comment (leibnitz27) [reply olewoo_interop/typestring.cpp:87]: I know - it looks odd - however I'm going by the output that oleview generates.  
(try it on the dll attached to the PR!)

Comment (bclothier) [reply olewoo_interop/typestring.cpp:87]: Hmm. Now I'm doubting the specifications because `byte` isn't a C/C++ data type. 

From [Windows Data Types](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types#BYTE):
```
A byte (8 bits).
This type is declared in WinDef.h as follows:
typedef unsigned char BYTE;
```

I don't see any evidence of `byte` being a C/C++ native data type. Therefore, I think `typedef byte BYTE;` is invalid, so I guess we're in agreement now.
